//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Windows.Installer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Windows.Installer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to Windows Installer PowerShell Extensions.
        /// </summary>
        internal static string SnapIn_Description {
            get {
                return ResourceManager.GetString("SnapIn_Description", resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to Microsoft Corporation.
        /// </summary>
        internal static string SnapIn_Vendor {
            get {
                return ResourceManager.GetString("SnapIn_Vendor", resourceCulture);
            }
        }

		/// <summary>
		/// Looks up a localized string similar to Invalid combination of user SID and install context.
		/// </summary>
		internal static string Argument_InvalidContextAndSid {
			get {
				return ResourceManager.GetString("Argument_InvalidContextAndSid", resourceCulture);
			}
		}

		/// <summary>
		/// Looks up a localized string similar to Invalid source format.
		/// </summary>
		internal static string Argument_InvalidSource {
			get {
				return ResourceManager.GetString("Argument_InvalidSource", resourceCulture);
			}
		}

		/// <summary>
		/// Looks up a localized string similar to Invalid source type.
		/// </summary>
		internal static string Argument_InvalidSourceType {
			get { 
				return ResourceManager.GetString("Argument_InvalidSourceType", resourceCulture);
			}
		}

		/// <summary>
		/// Looks up a localized string similar to Invalid product state.
		/// </summary>
		internal static string Argument_InvalidProductState {
			get {
					return ResourceManager.GetString("Argument_InvalidProductState", resourceCulture);
			}
		}
		
		internal static string MsiRequiredVersion(int major, int minor)
		{
			string format = ResourceManager.GetString("MsiRequiredVersion", resourceCulture);
			return string.Format(resourceCulture, format, major, minor);
		}
    }
}
