//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Windows.Installer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Windows.Installer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid combination of user SID and install context..
        /// </summary>
        internal static string Argument_InvalidContextAndSid {
            get {
                return ResourceManager.GetString("Argument_InvalidContextAndSid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid product state..
        /// </summary>
        internal static string Argument_InvalidProductState {
            get {
                return ResourceManager.GetString("Argument_InvalidProductState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid source format..
        /// </summary>
        internal static string Argument_InvalidSource {
            get {
                return ResourceManager.GetString("Argument_InvalidSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid source type..
        /// </summary>
        internal static string Argument_InvalidSourceType {
            get {
                return ResourceManager.GetString("Argument_InvalidSourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumerates patches for everyone..
        /// </summary>
        internal static string GetPatch_Everyone {
            get {
                return ResourceManager.GetString("GetPatch_Everyone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limits patches for the given install state filter..
        /// </summary>
        internal static string GetPatch_Filter {
            get {
                return ResourceManager.GetString("GetPatch_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input object from the pipeline..
        /// </summary>
        internal static string GetPatch_InputObject {
            get {
                return ResourceManager.GetString("GetPatch_InputObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limits patches for the given installation context..
        /// </summary>
        internal static string GetPatch_InstallContext {
            get {
                return ResourceManager.GetString("GetPatch_InstallContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets patch information for the given package codes..
        /// </summary>
        internal static string GetPatch_PackageCode {
            get {
                return ResourceManager.GetString("GetPatch_PackageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumerates patches for the given product codes..
        /// </summary>
        internal static string GetPatch_ProductCode {
            get {
                return ResourceManager.GetString("GetPatch_ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limits patches for the given user SID..
        /// </summary>
        internal static string GetPatch_UserSid {
            get {
                return ResourceManager.GetString("GetPatch_UserSid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumerates product for everyone..
        /// </summary>
        internal static string GetProduct_Everyone {
            get {
                return ResourceManager.GetString("GetProduct_Everyone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input object from the pipeline..
        /// </summary>
        internal static string GetProduct_InputObject {
            get {
                return ResourceManager.GetString("GetProduct_InputObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limits products for the given installation context..
        /// </summary>
        internal static string GetProduct_InstallContext {
            get {
                return ResourceManager.GetString("GetProduct_InstallContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets product information for the given product code..
        /// </summary>
        internal static string GetProduct_ProductCode {
            get {
                return ResourceManager.GetString("GetProduct_ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limits products for the given user SID..
        /// </summary>
        internal static string GetProduct_UserSid {
            get {
                return ResourceManager.GetString("GetProduct_UserSid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get related product for the given upgrade code..
        /// </summary>
        internal static string GetRelatedProduct_UpgradeCode {
            get {
                return ResourceManager.GetString("GetRelatedProduct_UpgradeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumerates source information for everyone..
        /// </summary>
        internal static string GetSource_Everyone {
            get {
                return ResourceManager.GetString("GetSource_Everyone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input object from the pipeline..
        /// </summary>
        internal static string GetSource_InputObject {
            get {
                return ResourceManager.GetString("GetSource_InputObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limits source information for the given installation context..
        /// </summary>
        internal static string GetSource_InstallContext {
            get {
                return ResourceManager.GetString("GetSource_InstallContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets source paths for the given patch codes..
        /// </summary>
        internal static string GetSource_PatchCode {
            get {
                return ResourceManager.GetString("GetSource_PatchCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets source paths for the given product codes..
        /// </summary>
        internal static string GetSource_ProductCode {
            get {
                return ResourceManager.GetString("GetSource_ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limits source information for the given source type..
        /// </summary>
        internal static string GetSource_SourceType {
            get {
                return ResourceManager.GetString("GetSource_SourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limits source information for the given user SID..
        /// </summary>
        internal static string GetSource_UserSid {
            get {
                return ResourceManager.GetString("GetSource_UserSid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the path to an item. Wildcards are permitted..
        /// </summary>
        internal static string Location_Path {
            get {
                return ResourceManager.GetString("Location_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Installer {0}.{1} is required to execute this command..
        /// </summary>
        internal static string MsiRequiredVersion {
            get {
                return ResourceManager.GetString("MsiRequiredVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Installer PowerShell Extensions.
        /// </summary>
        internal static string SnapIn_Description {
            get {
                return ResourceManager.GetString("SnapIn_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Corporation.
        /// </summary>
        internal static string SnapIn_Vendor {
            get {
                return ResourceManager.GetString("SnapIn_Vendor", resourceCulture);
            }
        }
    }
}
