//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Windows.Installer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Windows.Installer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid combination of user SID and install context..
        /// </summary>
        internal static string Argument_InvalidContextAndSid {
            get {
                return ResourceManager.GetString("Argument_InvalidContextAndSid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid product state..
        /// </summary>
        internal static string Argument_InvalidProductState {
            get {
                return ResourceManager.GetString("Argument_InvalidProductState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid source format..
        /// </summary>
        internal static string Argument_InvalidSource {
            get {
                return ResourceManager.GetString("Argument_InvalidSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid source type..
        /// </summary>
        internal static string Argument_InvalidSourceType {
            get {
                return ResourceManager.GetString("Argument_InvalidSourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify to search all users..
        /// </summary>
        internal static string Context_Everyone {
            get {
                return ResourceManager.GetString("Context_Everyone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install context to limit the search..
        /// </summary>
        internal static string Context_InstallContext {
            get {
                return ResourceManager.GetString("Context_InstallContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User SID to limit the search..
        /// </summary>
        internal static string Context_UserSid {
            get {
                return ResourceManager.GetString("Context_UserSid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied..
        /// </summary>
        internal static string Error_AccessDenied {
            get {
                return ResourceManager.GetString("Error_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration data for patch {0} is corrupt..
        /// </summary>
        internal static string Error_BadPatchConfiguration {
            get {
                return ResourceManager.GetString("Error_BadPatchConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration data for product {0} is corrupt..
        /// </summary>
        internal static string Error_BadProductConfiguration {
            get {
                return ResourceManager.GetString("Error_BadProductConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &quot;{0}&quot; already exists..
        /// </summary>
        internal static string File_AlreadyExists {
            get {
                return ResourceManager.GetString("File_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &quot;{0}&quot; is not a structure storage file..
        /// </summary>
        internal static string File_NotStorage {
            get {
                return ResourceManager.GetString("File_NotStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patch state filter to limit the search..
        /// </summary>
        internal static string GetPatch_Filter {
            get {
                return ResourceManager.GetString("GetPatch_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patch codes for which information is retrieved..
        /// </summary>
        internal static string GetPatch_PatchCode {
            get {
                return ResourceManager.GetString("GetPatch_PatchCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product codes for which patches are enumerated..
        /// </summary>
        internal static string GetPatch_ProductCode {
            get {
                return ResourceManager.GetString("GetPatch_ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product codes for which information is retrieved..
        /// </summary>
        internal static string GetProduct_ProductCode {
            get {
                return ResourceManager.GetString("GetProduct_ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade codes for which related products are enumerated..
        /// </summary>
        internal static string GetRelatedProduct_UpgradeCode {
            get {
                return ResourceManager.GetString("GetRelatedProduct_UpgradeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product or patch information object from the pipeline..
        /// </summary>
        internal static string GetSource_InputObject {
            get {
                return ResourceManager.GetString("GetSource_InputObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patch codes for which source list information is retrieved..
        /// </summary>
        internal static string GetSource_PatchCode {
            get {
                return ResourceManager.GetString("GetSource_PatchCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product codes for which source list information is retrieved..
        /// </summary>
        internal static string GetSource_ProductCode {
            get {
                return ResourceManager.GetString("GetSource_ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source type to limit the search..
        /// </summary>
        internal static string GetSource_SourceType {
            get {
                return ResourceManager.GetString("GetSource_SourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the path to an item. Wildcards are not permitted..
        /// </summary>
        internal static string Location_LiteralPath {
            get {
                return ResourceManager.GetString("Location_LiteralPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the path to an item. Wildcards are permitted..
        /// </summary>
        internal static string Location_Path {
            get {
                return ResourceManager.GetString("Location_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Installer {0}.{1} is required to execute this command..
        /// </summary>
        internal static string MsiRequiredVersion {
            get {
                return ResourceManager.GetString("MsiRequiredVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinstall the product with REINSTALLMODE=vomus..
        /// </summary>
        internal static string Recommend_Recache {
            get {
                return ResourceManager.GetString("Recommend_Recache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run the expression again in an elevated process..
        /// </summary>
        internal static string Recommend_RunElevated {
            get {
                return ResourceManager.GetString("Recommend_RunElevated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Installer PowerShell Extensions.
        /// </summary>
        internal static string SnapIn_Description {
            get {
                return ResourceManager.GetString("SnapIn_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Corporation.
        /// </summary>
        internal static string SnapIn_Vendor {
            get {
                return ResourceManager.GetString("SnapIn_Vendor", resourceCulture);
            }
        }
    }
}
